# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20160525_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
