# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='resolution',
        ),
    ]
