# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.BooleanField(default=0),
        ),
    ]
