# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='priority',
            new_name='hight_priority',
        ),
    ]
