# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 10, 22, 43, 568000)),
        ),
    ]
