# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_ticketuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketUser',
            new_name='TicketUserDetail',
        ),
    ]
