# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_auto_20160527_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='members',
            new_name='user_detail',
        ),
    ]
