# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='comment',
            new_name='reply',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='docfile',
        ),
    ]
