# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_attachment_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
