# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_remove_ticket_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='caca',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
