# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_ticket_caca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='caca',
        ),
    ]
